table simulations
	lineageTag: a4000001-0000-0000-0000-000000000004

	column snapshotDateUtc
		dataType: dateTime
		lineageTag: a4010001-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: snapshotDateUtc

		annotation SummarizationSetBy = Automatic

	column simulationId
		dataType: string
		lineageTag: a4010002-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: simulationId

		annotation SummarizationSetBy = Automatic

	column displayName
		dataType: string
		lineageTag: a4010003-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: a4010004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: a4010005-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column attackType
		dataType: string
		lineageTag: a4010006-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: attackType

		annotation SummarizationSetBy = Automatic

	column attackTechnique
		dataType: string
		lineageTag: a4010007-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: attackTechnique

		annotation SummarizationSetBy = Automatic

	column createdDateTime
		dataType: dateTime
		lineageTag: a4010008-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: createdDateTime

		annotation SummarizationSetBy = Automatic

	column launchDateTime
		dataType: dateTime
		lineageTag: a4010009-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: launchDateTime

		annotation SummarizationSetBy = Automatic

	column completionDateTime
		dataType: dateTime
		lineageTag: a4010010-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: completionDateTime

		annotation SummarizationSetBy = Automatic

	column lastModifiedDateTime
		dataType: dateTime
		lineageTag: a4010011-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: lastModifiedDateTime

		annotation SummarizationSetBy = Automatic

	column isAutomated
		dataType: boolean
		lineageTag: a4010012-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: isAutomated

		annotation SummarizationSetBy = Automatic

	column automationId
		dataType: string
		lineageTag: a4010013-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: automationId

		annotation SummarizationSetBy = Automatic

	column durationInDays
		dataType: int64
		formatString: 0
		lineageTag: a4010014-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: durationInDays

		annotation SummarizationSetBy = Automatic

	column payloadId
		dataType: string
		lineageTag: a4010015-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: payloadId

		annotation SummarizationSetBy = Automatic

	column payloadDisplayName
		dataType: string
		lineageTag: a4010016-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: payloadDisplayName

		annotation SummarizationSetBy = Automatic

	column reportTotalUserCount
		dataType: int64
		formatString: 0
		lineageTag: a4010017-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: reportTotalUserCount

		annotation SummarizationSetBy = Automatic

	column reportCompromisedCount
		dataType: int64
		formatString: 0
		lineageTag: a4010018-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: reportCompromisedCount

		annotation SummarizationSetBy = Automatic

	column reportClickCount
		dataType: int64
		formatString: 0
		lineageTag: a4010019-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: reportClickCount

		annotation SummarizationSetBy = Automatic

	column reportReportedCount
		dataType: int64
		formatString: 0
		lineageTag: a4010020-0000-0000-0000-000000000004
		summarizeBy: sum
		sourceColumn: reportReportedCount

		annotation SummarizationSetBy = Automatic

	column createdById
		dataType: string
		lineageTag: a4010021-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: createdById

		annotation SummarizationSetBy = Automatic

	column createdByDisplayName
		dataType: string
		lineageTag: a4010022-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: createdByDisplayName

		annotation SummarizationSetBy = Automatic

	column createdByEmail
		dataType: string
		lineageTag: a4010023-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: createdByEmail

		annotation SummarizationSetBy = Automatic

	column lastModifiedById
		dataType: string
		lineageTag: a4010024-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: lastModifiedById

		annotation SummarizationSetBy = Automatic

	column lastModifiedByDisplayName
		dataType: string
		lineageTag: a4010025-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: lastModifiedByDisplayName

		annotation SummarizationSetBy = Automatic

	column lastModifiedByEmail
		dataType: string
		lineageTag: a4010026-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: lastModifiedByEmail

		annotation SummarizationSetBy = Automatic

	partition simulations = m
		mode: import
		source =
			let
			    Source = AzureStorage.DataLake(StorageAccountUrl),
			    Container = Source{[Name=ContainerName]}[Content],
			    Filtered = Table.SelectRows(Container, each Text.StartsWith([Folder Path], ContainerName & "/simulations/")),
			    Sorted = Table.Sort(Filtered, {{"Date modified", Order.Descending}}),
			    Latest = Sorted{0}[Content],
			    Result = Parquet.Document(Latest)
			in
			    Result

	annotation PBI_ResultType = Table
