table trainingUserCoverage
	lineageTag: a3000001-0000-0000-0000-000000000003

	column snapshotDateUtc
		dataType: dateTime
		lineageTag: a3010001-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: snapshotDateUtc

		annotation SummarizationSetBy = Automatic

	column userId
		dataType: string
		lineageTag: a3010002-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: userId

		annotation SummarizationSetBy = Automatic

	column displayName
		dataType: string
		lineageTag: a3010003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: a3010004-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column assignedTrainingsCount
		dataType: int64
		formatString: 0
		lineageTag: a3010005-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: assignedTrainingsCount

		annotation SummarizationSetBy = Automatic

	column completedTrainingsCount
		dataType: int64
		formatString: 0
		lineageTag: a3010006-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: completedTrainingsCount

		annotation SummarizationSetBy = Automatic

	column inProgressTrainingsCount
		dataType: int64
		formatString: 0
		lineageTag: a3010007-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: inProgressTrainingsCount

		annotation SummarizationSetBy = Automatic

	column notStartedTrainingsCount
		dataType: int64
		formatString: 0
		lineageTag: a3010008-0000-0000-0000-000000000003
		summarizeBy: sum
		sourceColumn: notStartedTrainingsCount

		annotation SummarizationSetBy = Automatic

	partition trainingUserCoverage = m
		mode: import
		source =
			let
			    Source = AzureStorage.DataLake(StorageAccountUrl),
			    Container = Source{[Name=ContainerName]}[Content],
			    Filtered = Table.SelectRows(Container, each Text.StartsWith([Folder Path], ContainerName & "/trainingUserCoverage/")),
			    Sorted = Table.Sort(Filtered, {{"Date modified", Order.Descending}}),
			    Latest = Sorted{0}[Content],
			    Result = Parquet.Document(Latest)
			in
			    Result

	annotation PBI_ResultType = Table
